main:
  push: &build
    - name: Build
      retry: 1
      docker:
        image: eclipse-temurin:21-jdk
        volumes:
          - /root/.gradle
      stages:
        - name: Make Gradle wrapper executable
          script: chmod +x ./gradlew
        - name: Build with Gradle
          script: ./gradlew build
          timeout: 10m
        - name: Upload build artifacts
          image: cnbcool/attachments:latest
          allowFailure: true
          settings:
            attachments:
              - build/libs/*.jar
  pull_request: *build

$:
  tag_push:
    - name: Build and Release
      retry: 1
      docker:
        image: eclipse-temurin:21-jdk
        volumes:
          - /root/.gradle
      stages:
        - name: Make Gradle wrapper executable
          script: chmod +x ./gradlew
        - name: Build with Gradle
          script: ./gradlew build
          timeout: 10m
        - name: Generate changelog
          image: cnbcool/changelog:latest
          settings:
            latestChangeLogTarget: LATEST_CHANGELOG.md
        - name: Create Release
          type: git:release
          options:
            title: $CNB_BRANCH
            descriptionFromFile: LATEST_CHANGELOG.md
        - name: Upload build artifacts
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - build/libs/*.jar
